### PR TITLE
Ui/sign up screen

### PR DESCRIPTION
**Pull request by andela-cofor**
#### What does this PR do?
Build the blackbox signup screen displayed to a user

#### Description of Task to be completed?
* The user interface for blackbox signup screen should be designed.

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### Screenshots 
screen shot 2017-10-18 at 6 31 16 pm
#### Questions:
N/A

### CODE REVIEW

**Comment by oofoamalu** [comment]
Hmm... @andela-cofor Why did you open a pr for sign up screen? I thought this was already reviewed and merged to develop. If not, why do other branches have this feature then?

**Comment by andela-cofor** [comment]
@oofoamalu I think you are referring to login screen, and yes it was merged at the beginning of the project, because launch screen was supposed to lead you to login screen, but the login screen ui and features have not been merged only the activity was created, that is why others have the blank activity of login screen

**Review by oofoamalu — APPROVED** [review]
Nicely done 👍

**Comment by andela-cofor** [comment]
Thanks you @oofoamalu

**Pull request merged**
